# Generated by Django 3.2.25 on 2024-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
